# Generated by Django 3.2 on 2023-04-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.AlterField(
            model_name='room',
            name='unique_link',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
